### ISSUE TITLE
change --tool to --plugin?

### ISSUE THREAD

**Issue by wangbj** [iu-parfunc/systrace#26]
It seems more fit to name it as `--plugin` instead, what do you think?

**Comment by rrnewton** [comment]
I was thinking "tool" just because they call them "Pin tools".  @chamibuddhika, you've used a *lot* of these different systems, what are some of the names for the instrumentation tools that run on the instrumentation framework?

Plugin seems to imply that more than one can be plugged in (maybe tool does too? but less so)... we only support one instrumentation tool.   In principle, you could support multiple, with setting up trampolines that call more than one function that is "subscribed" to an event.  But that is a lot of complexity for something we don't have a use case for ;-).

**Comment by chamibuddhika** [comment]
AFAIK here is some terminology that I've encountered.

Pin - Tool
DynamoRIO - Client
Dyninst - Snippet (This is more like at API level so not that relavant)

Yeah multiple tools would be an advanced use which I feel will bring some (non trivial) complexity. I remember thinking about this kind of thing when I was thinking up an API for liteinst and realizing it could get complicated real fast (at least in liteinst setup where instrumentation can be toggled on and off periodically).

**Comment by wangbj** [comment]
Got it, will stick with `--tool` for now.
